apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-server-config
  labels:
    app: resource-server
    env: "${CI_ENVIRONMENT_SLUG}"
    tier: backend
data:
  DATABASE_HOST: "${CI_DATABASE_HOST}"
  DATABASE_PORT: "${CI_DATABASE_PORT}"
  DATABASE_USER: "${CI_DATABASE_USER}"
  DATABASE_PASSWORD: "${CI_DATABASE_PASSWORD}"
  DATABASE_SID: "${CI_DATABASE_SID}"
  FLYWAY_ENABLED: true
