apiVersion: v1
kind: Service
metadata:
  name: resource-server
spec:
  selector:
    app: resource-server
    env: "${CI_ENVIRONMENT_SLUG}"
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080
      name: resource-server
      protocol: TCP
  type: NodePort
