apiVersion: v1
kind: ConfigMap
metadata:
  name: "${artifactId}"
data:
  DATABASE_HOST: "${CI_DATABASE_HOST}"
  DATABASE_PORT: "${CI_DATABASE_PORT}"
  DATABASE_USER: "${CI_DATABASE_USER}"
  DATABASE_PASSWORD: "${CI_DATABASE_PASSWORD}"
  DATABASE_NAME: "${CI_DATABASE_NAME}"
