apiVersion: v1
kind: ConfigMap
metadata:
  name: ${artifactId}
data:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_USER: "secretPostgrePassword"
  DATABASE_PASSWORD: "postgres_user"
  DATABASE_NAME: "example"
  FLYWAY_ENABLED: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
data:
  POSTGRES_PASSWORD: secretPostgrePassword
  POSTGRES_USER: postgres_user
  POSTGRES_DB: example
