variables:
  MAVEN_VERSION: "3.6.3-jdk-11"
  MAVEN_CLI_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

.test-junit-auth-oracle:
  image: ${PRIVATE_REGISTRY_PULL}/maven:${MAVEN_VERSION}
  services:
    - name: ${PRIVATE_REGISTRY_PULL}/oracle/database:${ORACLE_VERSION}
      alias: oracledb
  variables:
    ORACLE_VERSION: 18.4.0-xe
    ORACLE_PWD: passwordnyaOracle2020
    DATABASE_HOST: oracledb
    DATABASE_USER: system
    DATABASE_PASSWORD: $ORACLE_PWD
    DATABASE_SID: xe
    DATABASE_PORT: 1521
#  script:
#    - mvn -s $M2_PROXY_XML $MAVEN_CLI_OPTS clean jacoco:prepare-agent test jacoco:report
#  after_script:
#    - mvn -s $M2_PROXY_XML sonar:sonar -Dsonar.projectKey=$CI_PROJECT_ID-$CI_DEFAULT_BRANCH -Dsonar.host.url=$URL_SONAR -Dsonar.login=$AUTH_SONAR -Dmaven.test.failure.ignore=false
#  tags:
#    - docker
#  only:
#    - /-release/
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

