application:
  developer:
    name: @team.name@
    email: @team.email@
    organisation: @team.organisation@
    organisation-url: @team.organization.url@
  license:
    name: @license.name@
    url: @license.url@
server:
  port: ${APPLICATION_PORT:9090}
spring:
  application:
    name: @project.artifactId@
    version: @project.version@
    fullname: @project.name@
  mvc:
    dispatch-options-request: true
  datasource:
    url: jdbc:oracle:thin:@${DATABASE_HOST:localhost}:${DATABASE_PORT:1521}:${DATABASE_SID:xe}
    username: ${DATABASE_USER:testing}
    password: ${DATABASE_PASSWORD:testing}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true
        enable_lazy_load_no_trans: true
        id:
          new_generator_mappings: false
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        globally_quoted_identifiers: true
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    encoding: UTF-8
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: true
    check-location: true
    locations: classpath:/db/migration
    clean-disabled: false
    clean-on-validation-error: true
    connect-retries: 3
  thymeleaf:
    enable-spring-el-compiler: true
    enabled: true
    cache: false
    check-template: true
    encoding: UTF-8
    mode: HTML
    suffix: .html
    servlet:
      content-type: text/html
    check-template-location: true
    template-resolver-order: 0
logging:
  level:
    org.springframework: ERROR
    com.tabeldata: ${LOG_LEVEL:DEBUG}
