version: '3.9'
services:
  minio-server:
    image: ${PRIVATE_REPOSITORY}/minio/minio
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      - MINIO_SITE_NAME
      - MINIO_SITE_REGION
    ports:
      - "9000:9000"
      - "9001:9001"
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - minio-bucket:/data

volumes:
  minio-bucket:
