version: '3.7'
services:
  postgres:
    image: ${private_repository}/postgres:${postgres_version}
    environment:
      - POSTGRES_PASSWORD=oauth2
      - POSTGRES_USER=oauth2
      - POSTGRES_DB=oauth2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
