apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${artifactId}
  labels:
    app: ${artifactId}
spec:
  replicas: 1
  template:
    metadata:
      name: ${artifactId}
      labels:
        app: ${artifactId}
    spec:
      containers:
        - name: ${artifactId}
          image: "tabeldata.ip-dynamic.com:8087/${project.groupId}/${artifactId}:${project.version}"
          imagePullPolicy: "Always"
          envFrom:
            - configMapRef:
                name: ${artifactId}
  selector:
    matchLabels:
      app: ${artifactId}
