apiVersion: v1
kind: Service
metadata:
  name: "${artifactId}"
spec:
  selector:
    app: "${artifactId}"
  ports:
    - port: 8080
      targetPort: 8080
      name: http
      protocol: TCP
  type: NodePort
