apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: postgres
      restartPolicy: Always
  selector:
    matchLabels:
      app: postgres
