apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${artifactId}
spec:
  template:
    spec:
      containers:
        - name: ${artifactId}
          image: ${PRIVATE_REGISTRY_PULL}/${CI_REGISTRY_NAMESPACE}/${CI_REGISTRY_IMAGE}:${CI_IMAGE_VERSION}
      imagePullSecrets:
        - name: ${DOCKER_REGCRED}
